# Generated by Django 2.1.5 on 2019-03-11 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caleg', '0001_initial'),
        ('tps', '__first__'),
        ('dapil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField()),
                ('pict', models.ImageField(upload_to='upload_pict/')),
                ('caleg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caleg.Caleg')),
                ('dapil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dapil.Dapil')),
                ('tps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tps.Tps')),
            ],
        ),
    ]
