# Generated by Django 2.1.7 on 2019-03-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_suara', models.IntegerField()),
                ('pict', models.ImageField(upload_to='upload_pict/')),
            ],
        ),
    ]
