# Generated by Django 2.1.7 on 2019-04-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suara',
            name='create_add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
