# Generated by Django 2.1.5 on 2019-03-12 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suara', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suara',
            name='dapil',
        ),
    ]
