# Generated by Django 2.1.5 on 2019-03-12 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suara', '0002_remove_suara_dapil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suara',
            name='caleg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suaras', to='caleg.Caleg'),
        ),
    ]
