# Generated by Django 2.1.5 on 2019-03-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suara', '0003_auto_20190312_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suara',
            name='tps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suaras', to='tps.Tps'),
        ),
    ]
