# Generated by Django 2.1.7 on 2019-04-15 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suara', '0003_suara_kelurahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suara',
            name='caleg',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suaras', to='caleg.Caleg'),
        ),
    ]
