# Generated by Django 2.1.7 on 2019-03-31 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kelurahan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.CharField(blank=True, max_length=100, null=True)),
                ('nama', models.CharField(max_length=100)),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kelurahan.Kelurahan')),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
    ]
