# Generated by Django 2.1.5 on 2019-03-14 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0002_auto_20190312_0754'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='tps',
            order_with_respect_to='kecamatan',
        ),
    ]
