# Generated by Django 2.1.7 on 2019-04-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190401_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='gambar',
            field=models.ImageField(default='default/default-user.png', upload_to='upload_pict/'),
        ),
    ]
